<?php

namespace Database\Seeders;

use App\Models\Driver;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class DriverSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $drivers = [
            ['department_id' => '1' , 'name' => 'سلطان مشعل سلطان' , 'title_id' => '1' ],
            ['department_id' => '1' , 'name' => 'محمد عبداللة شداد' , 'title_id' => '2' ],
            ['department_id' => '1' , 'name' => 'عرفة ممدوح' , 'title_id' => '3' ],
            ['department_id' => '1' , 'name' => 'ابو محمود' , 'title_id' => '4' ],
            ['department_id' => '2' , 'name' => 'سامي سالم عوده موسي' , 'title_id' => '5' ],
            ['department_id' => '2' , 'name' => 'محمد نبيه' , 'title_id' => '6' ],
            ['department_id' => '2' , 'name' => 'مصطفي ممدوح' , 'title_id' => '5' ],
            ['department_id' => '2' , 'name' => 'احمد رفعت ' , 'title_id' => '5' ],
            ['department_id' => '3' , 'name' => 'احمد ابراهيم  ' , 'title_id' => '7' ],
            ['department_id' => '3' , 'name' => 'عبدالله الجويرد' , 'title_id' => '8' ],
            ['department_id' => '3' , 'name' => 'سناء متعب شهاب الشمري ' , 'title_id' => '9' ],
            ['department_id' => '3' , 'name' => 'عمر بدوي ' , 'title_id' => '8' ],
            ['department_id' => '4' , 'name' => 'نبيل فراج' , 'title_id' => '10' ],
            ['department_id' => '4' , 'name' => 'احمد مهران' , 'title_id' => '11' ],
            ['department_id' => '4' , 'name' => 'محمود عبد الفتاح' , 'title_id' => '10' ],
            ['department_id' => '4' , 'name' => 'فياز' , 'title_id' => '11' ],
            ['department_id' => '4' , 'name' => 'أحمد خطاب' , 'title_id' => '11' ],
            ['department_id' => '4' , 'name' => 'باثوراما كريشنا' , 'title_id' => '10' ],
            ['department_id' => '4' , 'name' => 'جورديب' , 'title_id' => '11' ],
            ['department_id' => '4' , 'name' => 'هيثم خلف' , 'title_id' => '10' ],
            ['department_id' => '4' , 'name' => 'فياج انصاري' , 'title_id' => '11' ],
            ['department_id' => '4' , 'name' => 'سامح حمدي' , 'title_id' => '10' ],
            ['department_id' => '4' , 'name' => 'محمد سامي' , 'title_id' => '11' ],
            ['department_id' => '4' , 'name' => 'محمود السيد عبد العاطي' , 'title_id' => '10' ],
            ['department_id' => '4' , 'name' => 'احمد محمد عبد الفتاح' , 'title_id' => '11' ],
            ['department_id' => '4' , 'name' => 'رضا محمود ابراهيم' , 'title_id' => '10' ],
            ['department_id' => '4' , 'name' => 'شريف محمد الصغير' , 'title_id' => '11' ],
            ['department_id' => '4' , 'name' => 'حمدي محمد ' , 'title_id' => '11' ],
            ['department_id' => '4' , 'name' => 'هاني عبدالحفيظ' , 'title_id' => '12' ],
            ['department_id' => '4' , 'name' => 'فرج عشري ' , 'title_id' => '10' ],
            ['department_id' => '4' , 'name' => 'حسام ايمن' , 'title_id' => '11' ],
            ['department_id' => '4' , 'name' => 'احمد عنتر كامل' , 'title_id' => '11' ],
            ['department_id' => '4' , 'name' => 'عبدالفتاح سعد' , 'title_id' => '10' ],
            ['department_id' => '4' , 'name' => 'نور علام ' , 'title_id' => '11' ],
            ['department_id' => '4' , 'name' => 'اسلام فايز' , 'title_id' => '10' ],
            ['department_id' => '4' , 'name' => 'ام دي ميراج' , 'title_id' => '11' ],
            ['department_id' => '4' , 'name' => 'احمد مزيون' , 'title_id' => '11' ],
            ['department_id' => '4' , 'name' => 'محمد مدثر' , 'title_id' => '10' ],
            ['department_id' => '4' , 'name' => 'عبد الله كريم' , 'title_id' => '11' ],
            ['department_id' => '4' , 'name' => 'ياسر محمود' , 'title_id' => '11' ],
            ['department_id' => '4' , 'name' => 'محمود علي أحمد' , 'title_id' => '10' ],
            ['department_id' => '4' , 'name' => 'عبدالله اسعد' , 'title_id' => '11' ],
            ['department_id' => '4' , 'name' => 'ساجد داف' , 'title_id' => '10' ],
            ['department_id' => '4' , 'name' => 'ردشسام' , 'title_id' => '11' ],
            ['department_id' => '4' , 'name' => 'مصطفي محرم' , 'title_id' => '10' ],
            ['department_id' => '4' , 'name' => 'رامبوبو' , 'title_id' => '11' ],
            ['department_id' => '4' , 'name' => 'محمد صبري' , 'title_id' => '10' ],
            ['department_id' => '4' , 'name' => 'مسعود يوسف ' , 'title_id' => '11' ],
            ['department_id' => '4' , 'name' => 'محمود زهري ' , 'title_id' => '11' ],
            ['department_id' => '4' , 'name' => 'عبد العزيز احمد ' , 'title_id' => '11' ],
            ['department_id' => '5' , 'name' => 'احمد وهيب' , 'title_id' => '10' ],
            ['department_id' => '5' , 'name' => 'محمد صابر' , 'title_id' => '11' ],
            ['department_id' => '5' , 'name' => 'عزت خيري احمد' , 'title_id' => '11' ],
            ['department_id' => '5' , 'name' => 'احمد محمد عبدالله' , 'title_id' => '10' ],
            ['department_id' => '5' , 'name' => 'وليد احمد  ' , 'title_id' => '11' ],
            ['department_id' => '5' , 'name' => 'فراج عثمان' , 'title_id' => '10' ],
            ['department_id' => '5' , 'name' => 'علي عبداللاه' , 'title_id' => '11' ],
            ['department_id' => '5' , 'name' => 'زكي محمد' , 'title_id' => '10' ],
            ['department_id' => '5' , 'name' => 'هيمانس ' , 'title_id' => '11' ],
            ['department_id' => '5' , 'name' => 'صالح كامل' , 'title_id' => '10' ],
            ['department_id' => '5' , 'name' => 'سيد شريف ' , 'title_id' => '11' ],
            ['department_id' => '5' , 'name' => 'محمد سليم' , 'title_id' => '10' ],
            ['department_id' => '5' , 'name' => 'وسيم اكرم' , 'title_id' => '11' ],
            ['department_id' => '5' , 'name' => 'محمود حسن' , 'title_id' => '10' ],
            ['department_id' => '5' , 'name' => 'اسلام بدر' , 'title_id' => '11' ],
            ['department_id' => '5' , 'name' => 'سيد عز الدين' , 'title_id' => '10' ],
            ['department_id' => '5' , 'name' => 'محمد دلشاد ' , 'title_id' => '11' ],
            ['department_id' => '5' , 'name' => 'هشام تغيان' , 'title_id' => '10' ],
            ['department_id' => '5' , 'name' => 'فايز محمد' , 'title_id' => '11' ],
            ['department_id' => '5' , 'name' => 'الطيب محمد' , 'title_id' => '10' ],
            ['department_id' => '5' , 'name' => 'محمد مسعود' , 'title_id' => '11' ],
            ['department_id' => '5' , 'name' => 'عمرو سلامة' , 'title_id' => '10' ],
            ['department_id' => '5' , 'name' => 'راج  ' , 'title_id' => '11' ],
            ['department_id' => '5' , 'name' => 'محمد محمد علي' , 'title_id' => '11' ],
            ['department_id' => '5' , 'name' => 'راجا كامورثي' , 'title_id' => '10' ],
            ['department_id' => '5' , 'name' => 'حازم مدوخي ' , 'title_id' => '11' ],
            ['department_id' => '5' , 'name' => 'اجمير' , 'title_id' => '10' ],
            ['department_id' => '5' , 'name' => 'حمزه قرامي ' , 'title_id' => '11' ],
            ['department_id' => '5' , 'name' => 'السيد محمود' , 'title_id' => '10' ],
            ['department_id' => '5' , 'name' => 'محمد عزام ' , 'title_id' => '11' ],
            ['department_id' => '5' , 'name' => 'بدر شحاتة' , 'title_id' => '11' ],
            ['department_id' => '6' , 'name' => 'محمد رفاعي' , 'title_id' => '10' ],
            ['department_id' => '6' , 'name' => 'بافندر' , 'title_id' => '11' ],
            ['department_id' => '6' , 'name' => 'ابراهيم احمد عبدالله' , 'title_id' => '10' ],
            ['department_id' => '6' , 'name' => 'جوربريت' , 'title_id' => '11' ],
            ['department_id' => '6' , 'name' => 'هاني ابراهيم' , 'title_id' => '10' ],
            ['department_id' => '6' , 'name' => 'مؤمن رفعت' , 'title_id' => '11' ],
            ['department_id' => '6' , 'name' => 'محمود سيف النصر' , 'title_id' => '10' ],
            ['department_id' => '6' , 'name' => 'مروان مصطفي  ' , 'title_id' => '11' ],
            ['department_id' => '6' , 'name' => 'عاطف عبدالله' , 'title_id' => '10' ],
            ['department_id' => '6' , 'name' => 'احمد جابر' , 'title_id' => '11' ],
            ['department_id' => '6' , 'name' => 'كريم محمد امين' , 'title_id' => '11' ],
            ['department_id' => '6' , 'name' => 'محمد سمك' , 'title_id' => '11' ],
            ['department_id' => '6' , 'name' => 'كرمال شيخ' , 'title_id' => '10' ],
            ['department_id' => '6' , 'name' => 'حسام الشائب ' , 'title_id' => '11' ],
            ['department_id' => '7' , 'name' => 'فهد بخيت' , 'title_id' => '11' ],
            ['department_id' => '7' , 'name' => 'مصطفي عبد الهادي' , 'title_id' => '10' ],
            ['department_id' => '7' , 'name' => 'محمد سمير' , 'title_id' => '11' ],
            ['department_id' => '7' , 'name' => 'ادهم هلب' , 'title_id' => '10' ],
            ['department_id' => '7' , 'name' => 'رافي جودام' , 'title_id' => '11' ],
            ['department_id' => '7' , 'name' => 'عبيد حمدان' , 'title_id' => '10' ],
            ['department_id' => '7' , 'name' => 'محمود عفيفي ' , 'title_id' => '11' ],
            ['department_id' => '8' , 'name' => 'عتمان عزب' , 'title_id' => '11' ],
            ['department_id' => '8' , 'name' => 'بارتاب ' , 'title_id' => '11' ],
            ['department_id' => '8' , 'name' => 'شكيل نور احمد' , 'title_id' => '11' ],
            ['department_id' => '8' , 'name' => 'امير بابا' , 'title_id' => '11' ],
            ['department_id' => '8' , 'name' => 'محمد الباز' , 'title_id' => '10' ],
            ['department_id' => '8' , 'name' => 'سيد اسف' , 'title_id' => '11' ],
            ['department_id' => '8' , 'name' => 'عز الدين كمال' , 'title_id' => '10' ],
            ['department_id' => '8' , 'name' => 'السيد امير ' , 'title_id' => '11' ],
            ['department_id' => '8' , 'name' => 'عبد الحكم' , 'title_id' => '10' ],
            ['department_id' => '8' , 'name' => 'سيد مختار ' , 'title_id' => '11' ],
            ['department_id' => '8' , 'name' => 'محمد عبدالغني' , 'title_id' => '10' ],
            ['department_id' => '8' , 'name' => 'محمد توفيق' , 'title_id' => '11' ],
            ['department_id' => '8' , 'name' => 'زين العابدين' , 'title_id' => '11' ],
            ['department_id' => '8' , 'name' => 'ساربجيت ' , 'title_id' => '11' ],
            ['department_id' => '8' , 'name' => 'محمد حمدان' , 'title_id' => '10' ],
            ['department_id' => '8' , 'name' => 'فيجاش كومار ' , 'title_id' => '11' ],
            ['department_id' => '8' , 'name' => 'علاء عبد التواب' , 'title_id' => '10' ],
            ['department_id' => '8' , 'name' => 'عبدول سيراج ' , 'title_id' => '11' ],
            ['department_id' => '8' , 'name' => 'شعبان خضر' , 'title_id' => '10' ],
            ['department_id' => '8' , 'name' => 'جري اباد جري' , 'title_id' => '11' ],
            ['department_id' => '8' , 'name' => 'هيتم عبد الرؤف' , 'title_id' => '10' ],
            ['department_id' => '8' , 'name' => 'محمود شعبان' , 'title_id' => '11' ],
            ['department_id' => '8' , 'name' => 'علاء عبد الحفيظ' , 'title_id' => '10' ],
            ['department_id' => '8' , 'name' => 'ملا عمران ' , 'title_id' => '11' ],
            ['department_id' => '8' , 'name' => 'خالد محمود' , 'title_id' => '10' ],
            ['department_id' => '8' , 'name' => 'كمال حسن ' , 'title_id' => '11' ],
            ['department_id' => '8' , 'name' => 'السيد حسين' , 'title_id' => '10' ],
            ['department_id' => '8' , 'name' => 'اشرف خميري ' , 'title_id' => '11' ],
            ['department_id' => '8' , 'name' => 'مصطفي ابوبكر' , 'title_id' => '11' ],
            ['department_id' => '8' , 'name' => 'بليفر' , 'title_id' => '11' ],
            ['department_id' => '8' , 'name' => 'الشريف محمد' , 'title_id' => '10' ],
            ['department_id' => '8' , 'name' => 'شريف السيد ' , 'title_id' => '11' ],
            ['department_id' => '8' , 'name' => 'حمدي محمود' , 'title_id' => '10' ],
            ['department_id' => '8' , 'name' => 'محبوب' , 'title_id' => '11' ],
            ['department_id' => '8' , 'name' => 'محمد عمر' , 'title_id' => '10' ],
            ['department_id' => '9' , 'name' => 'احمد محمد' , 'title_id' => '10' ],
            ['department_id' => '9' , 'name' => 'محمد طارق' , 'title_id' => '11' ],
            ['department_id' => '9' , 'name' => 'محمود جمال ' , 'title_id' => '13' ],
        ];

        foreach($drivers as $driver){
            Driver::create($driver);
        }
    }
}
